# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/liu/Documents/FTPServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/liu/Documents/FTPServer/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liu/Documents/FTPServer/build/CMakeFiles /home/liu/Documents/FTPServer/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liu/Documents/FTPServer/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FTPSERVER

# Build rule for target.
FTPSERVER: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FTPSERVER
.PHONY : FTPSERVER

# fast build rule for target.
FTPSERVER/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/build
.PHONY : FTPSERVER/fast

CMDRETR.o: CMDRETR.cpp.o
.PHONY : CMDRETR.o

# target to build an object file
CMDRETR.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/CMDRETR.cpp.o
.PHONY : CMDRETR.cpp.o

CMDRETR.i: CMDRETR.cpp.i
.PHONY : CMDRETR.i

# target to preprocess a source file
CMDRETR.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/CMDRETR.cpp.i
.PHONY : CMDRETR.cpp.i

CMDRETR.s: CMDRETR.cpp.s
.PHONY : CMDRETR.s

# target to generate assembly for a file
CMDRETR.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/CMDRETR.cpp.s
.PHONY : CMDRETR.cpp.s

CMDSTOR.o: CMDSTOR.cpp.o
.PHONY : CMDSTOR.o

# target to build an object file
CMDSTOR.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/CMDSTOR.cpp.o
.PHONY : CMDSTOR.cpp.o

CMDSTOR.i: CMDSTOR.cpp.i
.PHONY : CMDSTOR.i

# target to preprocess a source file
CMDSTOR.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/CMDSTOR.cpp.i
.PHONY : CMDSTOR.cpp.i

CMDSTOR.s: CMDSTOR.cpp.s
.PHONY : CMDSTOR.s

# target to generate assembly for a file
CMDSTOR.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/CMDSTOR.cpp.s
.PHONY : CMDSTOR.cpp.s

CloneFactory.o: CloneFactory.cpp.o
.PHONY : CloneFactory.o

# target to build an object file
CloneFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/CloneFactory.cpp.o
.PHONY : CloneFactory.cpp.o

CloneFactory.i: CloneFactory.cpp.i
.PHONY : CloneFactory.i

# target to preprocess a source file
CloneFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/CloneFactory.cpp.i
.PHONY : CloneFactory.cpp.i

CloneFactory.s: CloneFactory.cpp.s
.PHONY : CloneFactory.s

# target to generate assembly for a file
CloneFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/CloneFactory.cpp.s
.PHONY : CloneFactory.cpp.s

FTPTask.o: FTPTask.cpp.o
.PHONY : FTPTask.o

# target to build an object file
FTPTask.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/FTPTask.cpp.o
.PHONY : FTPTask.cpp.o

FTPTask.i: FTPTask.cpp.i
.PHONY : FTPTask.i

# target to preprocess a source file
FTPTask.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/FTPTask.cpp.i
.PHONY : FTPTask.cpp.i

FTPTask.s: FTPTask.cpp.s
.PHONY : FTPTask.s

# target to generate assembly for a file
FTPTask.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/FTPTask.cpp.s
.PHONY : FTPTask.cpp.s

FTPThread.o: FTPThread.cpp.o
.PHONY : FTPThread.o

# target to build an object file
FTPThread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/FTPThread.cpp.o
.PHONY : FTPThread.cpp.o

FTPThread.i: FTPThread.cpp.i
.PHONY : FTPThread.i

# target to preprocess a source file
FTPThread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/FTPThread.cpp.i
.PHONY : FTPThread.cpp.i

FTPThread.s: FTPThread.cpp.s
.PHONY : FTPThread.s

# target to generate assembly for a file
FTPThread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/FTPThread.cpp.s
.PHONY : FTPThread.cpp.s

FTPThreadPool.o: FTPThreadPool.cpp.o
.PHONY : FTPThreadPool.o

# target to build an object file
FTPThreadPool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/FTPThreadPool.cpp.o
.PHONY : FTPThreadPool.cpp.o

FTPThreadPool.i: FTPThreadPool.cpp.i
.PHONY : FTPThreadPool.i

# target to preprocess a source file
FTPThreadPool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/FTPThreadPool.cpp.i
.PHONY : FTPThreadPool.cpp.i

FTPThreadPool.s: FTPThreadPool.cpp.s
.PHONY : FTPThreadPool.s

# target to generate assembly for a file
FTPThreadPool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/FTPThreadPool.cpp.s
.PHONY : FTPThreadPool.cpp.s

FTPserver.o: FTPserver.cpp.o
.PHONY : FTPserver.o

# target to build an object file
FTPserver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/FTPserver.cpp.o
.PHONY : FTPserver.cpp.o

FTPserver.i: FTPserver.cpp.i
.PHONY : FTPserver.i

# target to preprocess a source file
FTPserver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/FTPserver.cpp.i
.PHONY : FTPserver.cpp.i

FTPserver.s: FTPserver.cpp.s
.PHONY : FTPserver.s

# target to generate assembly for a file
FTPserver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/FTPserver.cpp.s
.PHONY : FTPserver.cpp.s

FTPserverCMD.o: FTPserverCMD.cpp.o
.PHONY : FTPserverCMD.o

# target to build an object file
FTPserverCMD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/FTPserverCMD.cpp.o
.PHONY : FTPserverCMD.cpp.o

FTPserverCMD.i: FTPserverCMD.cpp.i
.PHONY : FTPserverCMD.i

# target to preprocess a source file
FTPserverCMD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/FTPserverCMD.cpp.i
.PHONY : FTPserverCMD.cpp.i

FTPserverCMD.s: FTPserverCMD.cpp.s
.PHONY : FTPserverCMD.s

# target to generate assembly for a file
FTPserverCMD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FTPSERVER.dir/build.make CMakeFiles/FTPSERVER.dir/FTPserverCMD.cpp.s
.PHONY : FTPserverCMD.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FTPSERVER"
	@echo "... CMDRETR.o"
	@echo "... CMDRETR.i"
	@echo "... CMDRETR.s"
	@echo "... CMDSTOR.o"
	@echo "... CMDSTOR.i"
	@echo "... CMDSTOR.s"
	@echo "... CloneFactory.o"
	@echo "... CloneFactory.i"
	@echo "... CloneFactory.s"
	@echo "... FTPTask.o"
	@echo "... FTPTask.i"
	@echo "... FTPTask.s"
	@echo "... FTPThread.o"
	@echo "... FTPThread.i"
	@echo "... FTPThread.s"
	@echo "... FTPThreadPool.o"
	@echo "... FTPThreadPool.i"
	@echo "... FTPThreadPool.s"
	@echo "... FTPserver.o"
	@echo "... FTPserver.i"
	@echo "... FTPserver.s"
	@echo "... FTPserverCMD.o"
	@echo "... FTPserverCMD.i"
	@echo "... FTPserverCMD.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

